site_name: flask-openapi3
site_url: https://luolingchun.github.io/flask-openapi3
site_description: Generate RESTful API and OpenAPI document for your Flask project.
site_author: llc

repo_url: https://github.com/luolingchun/flask-openapi3
repo_name: 'GitHub'

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true


theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo-blue.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light
  features:
    - navigation.tracking
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - mkdocstrings


extra_javascript:
  - js/db.js

extra_css:
  - css/img.css

nav:
  - Home: index.md
  - Quickstart: Quickstart.md
  - OpenAPI: OpenAPI.md
  - Example: Example.md
  - API Reference:
      - OpenAPI: Reference/OpenAPI.md
      - APIBlueprint: Reference/APIBlueprint.md
      - Model:
        - APISpec: Reference/Model/APISpec.md
        - common: Reference/Model/common.md
        - component: Reference/Model/component.md
        - file: Reference/Model/file.md
        - oauth: Reference/Model/oauth.md
        - parameter: Reference/Model/parameter.md
        - path: Reference/Model/path.md
        - security: Reference/Model/security.md
        - tag: Reference/Model/tag.md
        - validation_error: Reference/Model/validation_error.md
  - LICENSE: LICENSE.md
  - Changelog: Changelog.md

